development:
  adapter: postgresql
  encoding: unicode
  database: sherman_development
  pool: 5
  host: localhost
  username:  AdiSingh
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: sherman_test
  pool: 5
  host: localhost
  username:  AdiSingh
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: sherman_production
  pool: 5
  host: localhost
  username:  AdiSingh
  password: